version: "3.7"

services:
  app:
    restart: always
    build: .
    environment:
    - REDIS_HOST=redis
    env_file: # Pass the environment variables in the .env file to the container
      - .env
    ports:
      - 80:5000
    volumes:
      - ./:/app
    links:
      - redis

  
  redis:
    restart: always
    image: redis:5-alpine
    volumes:
      - 'redis:/data'
    ports:
      - 6379:6379


volumes:
  redis:
